export enum UserRole {
  USER = 'USER',
  ADMIN = 'ADMIN',
  MODERATOR = 'MODERATOR',
}

export enum AuthProvider {
  GOOGLE = 'GOOGLE',
  FACEBOOK = 'FACEBOOK',
  EMAIL = 'EMAIL',
}

export enum VideoSubtitleStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  READY = 'READY',
  FAILED = 'FAILED',
}

export enum VideoSubtitleType {
  AUTO_GENERATED = 'AUTO_GENERATED',
  COMMUNITY = 'COMMUNITY',
  OFFICIAL = 'OFFICIAL',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED',
  REFUNDED = 'REFUNDED',
}

export enum PaymentMethod {
  PAYOS = 'PAYOS',
}

export enum TransactionType {
  PURCHASE = 'PURCHASE',
  UNLOCK_VIDEO = 'UNLOCK_VIDEO',
  REFERRAL_BONUS = 'REFERRAL_BONUS',
  PIONEER_REWARD = 'PIONEER_REWARD',
  REFUND = 'REFUND',
  PROMOTION = 'PROMOTION',
}

export enum TransactionStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum FlashcardMasteryLevel {
  NEW = 'NEW',
  LEARNING = 'LEARNING',
  REVIEWING = 'REVIEWING',
  MASTERED = 'MASTERED',
}

export enum QuizType {
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
  FILL_BLANK = 'FILL_BLANK',
  MATCH_MEANING = 'MATCH_MEANING',
  CONTEXT_SENTENCE = 'CONTEXT_SENTENCE',
}

export enum NotificationType {
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  VIDEO_READY = 'VIDEO_READY',
  FLASHCARD_REMINDER = 'FLASHCARD_REMINDER',
  STREAK_REMINDER = 'STREAK_REMINDER',
  PROMOTION = 'PROMOTION',
  SYSTEM = 'SYSTEM',
}

export enum NotificationChannel {
  EMAIL = 'EMAIL',
  PUSH = 'PUSH',
  IN_APP = 'IN_APP',
}

export enum NotificationStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  FAILED = 'FAILED',
  READ = 'READ',
}

export enum AIJobStatus {
  QUEUED = 'QUEUED',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum AIJobType {
  WHISPER_TRANSCRIPTION = 'WHISPER_TRANSCRIPTION',
  TRANSLATION = 'TRANSLATION',
  VOCABULARY_ANALYSIS = 'VOCABULARY_ANALYSIS',
  QUIZ_GENERATION = 'QUIZ_GENERATION',
}

export enum AchievementType {
  FIRST_VIDEO = 'FIRST_VIDEO',
  STREAK_7_DAYS = 'STREAK_7_DAYS',
  STREAK_30_DAYS = 'STREAK_30_DAYS',
  FLASHCARD_100 = 'FLASHCARD_100',
  FLASHCARD_500 = 'FLASHCARD_500',
  QUIZ_PERFECT_SCORE = 'QUIZ_PERFECT_SCORE',
  VIDEOS_COMPLETED_10 = 'VIDEOS_COMPLETED_10',
  VIDEOS_COMPLETED_50 = 'VIDEOS_COMPLETED_50',
  COINS_EARNED_1000 = 'COINS_EARNED_1000',
}

export enum WatchStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
}

export enum AdminLogAction {
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
  USER_BAN = 'USER_BAN',
  USER_UNBAN = 'USER_UNBAN',
  PAYMENT_APPROVE = 'PAYMENT_APPROVE',
  PAYMENT_REJECT = 'PAYMENT_REJECT',
  AI_JOB_RETRY = 'AI_JOB_RETRY',
  AI_JOB_CANCEL = 'AI_JOB_CANCEL',
  FEATURE_TOGGLE = 'FEATURE_TOGGLE',
}
